### ISSUE TITLE
Ease troubleshooting of unit tests with calls to mock unstubbed methods

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-app-broker#350]
Currently, unit tests make heavy use of mocks. When mocks are improperly configured, calls to unstubbed methods return null, which is hard to diagnose with async reactor calls.

After adding `Hooks.onOperatorDebug();` stack trace such as the following are displayed, but **do not display the actual stubbed method call invocation, to ease comparison with mock setup**

```
25-03-2020 15:38:54.073 [main] ERROR o.s.c.a.w.i.AppDeploymentDeleteServiceInstanceWorkflow.error - Error deleting backing services for service1/plan1 with error 'The mapper returned a null Publisher.'
java.lang.NullPointerException: The mapper returned a null Publisher.
	at java.util.Objects.requireNonNull(Objects.java:228)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMapMany] :
	reactor.core.publisher.Mono.flatMapMany(Mono.java:2748)
	org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:71)
Error has been observed at the following site(s):
	|_  Mono.flatMapMany ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:71)
	|_      Flux.flatMap ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:75)
	|_  Flux.doOnRequest ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:76)
	|_ Flux.doOnComplete ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:78)
```

Possible improvement: systematically throw a exception is friendly message when an unstubbed method call invocation is received:

```
25-03-2020 15:42:11.499 [main] ERROR o.s.c.a.w.i.AppDeploymentDeleteServiceInstanceWorkflow.error - Error deleting backing services for service1/plan1 with error 'Unexpected call to unstubbed mock method: targetService.addToBackingServices(
    [BackingService{serviceInstanceName='my-service-instance', name='my-service', plan='a-plan', parameters={}, properties={}, parametersTransformers=[], rebindOnUpdate=false}],
    org.springframework.cloud.appbroker.deployer.TargetSpec@e67e89f4,
    "service-instance-id"
);'
java.lang.RuntimeException: Unexpected call to unstubbed mock method: targetService.addToBackingServices(
    [BackingService{serviceInstanceName='my-service-instance', name='my-service', plan='a-plan', parameters={}, properties={}, parametersTransformers=[], rebindOnUpdate=false}],
    org.springframework.cloud.appbroker.deployer.TargetSpec@e67e89f4,
    "service-instance-id"
);
	at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflowTest$RuntimeExceptionAnswer.answer(AppDeploymentDeleteServiceInstanceWorkflowTest.java:352)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMapMany] :
	reactor.core.publisher.Mono.flatMapMany(Mono.java:2748)
	org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:71)
Error has been observed at the following site(s):
	|_  Mono.flatMapMany ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:71)
	|_      Flux.flatMap ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:75)
	|_  Flux.doOnRequest ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:76)
	|_ Flux.doOnComplete ⇢ at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices(AppDeploymentDeleteServiceInstanceWorkflow.java:78)
```

This is supported through a custom default mockito answer, see https://stackoverflow.com/a/15835255/1484823

I applied this in a sample test in https://github.com/orange-cloudfoundry/osb-cmdb-spike/commit/b2324e4fb3edde4247071e11cc23ea8392952a1f#diff-4a2e062758255b0f47b073e44268b72c as part of #292

**Comment by gberche-orange** [comment]
Actually, mockito provides smart nulls which supports the `@Mockito` annotation, and is systematically used in cf-java-client, see https://github.com/cloudfoundry/cf-java-client/blob/8ec06b4cdd61dda0f0ba5e4d546651b880735faa/cloudfoundry-operations/src/test/java/org/cloudfoundry/operations/AbstractOperationsTest.java#L79-L97

```
    @Mock(answer = Answers.RETURNS_SMART_NULLS)
    private BackingAppDeploymentService backingAppDeploymentService;
```

It may be less strict than a custom Answer systematically throwing an exception, as it attempts to return first tries to return ordinary values for "empty" objects, thereby possibly still hiding some unstubbed methods

See https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#RETURNS_SMART_NULLS

>    If your code uses the object returned by an unstubbed call you get a NullPointerException. This implementation of Answer returns SmartNull instead of null. SmartNull gives nicer exception message than NPE because it points out the line where unstubbed method was called. You just click on the stack trace.
>
>    ReturnsSmartNulls first tries to return ordinary values (zeros, empty collections, empty string, etc.) then it tries to return SmartNull. If the return type is final then plain null is returned.
>
>    ReturnsSmartNulls will be probably the default return values strategy in Mockito 4.0.0

Here is a sample of such exception thrown with line navigation provided by intellij

![image](https://user-images.githubusercontent.com/4748380/77893616-6dac4280-7274-11ea-81ba-929f65357e0a.png)

See refined attempt at https://github.com/orange-cloudfoundry/osb-cmdb-spike/commit/bb8d5e9f4201735015798d575bab8ee23cba4cae 

The full exception is reproduced below
```
org.mockito.exceptions.verification.SmartNullPointerException: 
You have a NullPointerException here:
-> at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
because this method call was *not* stubbed correctly:
-> at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflow.lambda$deleteBackingServices$0(AppDeploymentDeleteServiceInstanceWorkflow.java:72)
targetService.addToBackingServices(
    [BackingService{serviceInstanceName='my-service-instance', name='my-service', plan='a-plan', parameters={}, properties={}, parametersTransformers=[], rebindOnUpdate=false}],
    org.springframework.cloud.appbroker.deployer.TargetSpec@e67e89f4,
    "service-instance-id"
);


	at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2199)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:134)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8174)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.toVerifierAndSubscribe(DefaultStepVerifierBuilder.java:867)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:823)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:815)
	at reactor.test.DefaultStepVerifierBuilder.verifyComplete(DefaultStepVerifierBuilder.java:682)
	at org.springframework.cloud.appbroker.workflow.instance.AppDeploymentDeleteServiceInstanceWorkflowTest.deleteServiceInstanceSucceeds(AppDeploymentDeleteServiceInstanceWorkflowTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

To apply smart nulls to all app broker tests requires converting tests using BDDMockito (in form of `given(object.method()).willReturn(value)` into `doReturn(value).when(object.method())`

As such manual conversion is time consumming, [intellij structural search and replace](https://www.jetbrains.com/help/idea/structural-search-and-replace.html) can mostly automate this

![image](https://user-images.githubusercontent.com/4748380/77896585-cda4e800-7278-11ea-9109-440bc63b25c4.png)

![image](https://user-images.githubusercontent.com/4748380/77896677-ef9e6a80-7278-11ea-9efc-118bb185287b.png)

![image](https://user-images.githubusercontent.com/4748380/77896823-1eb4dc00-7279-11ea-8e66-298251a5fce6.png)

Here is an export of this search/replace template which can be imported into intellij.
https://gist.github.com/gberche-orange/f3f8003349d8192c3b4a8237a2079223

If opting for the "use static imports" checkbox, then `Mockito` class specifier is omitted but also `Mono.empty()` becomes `empty()`

I'm happy to give it a try on the whole codebase once my outstanding PRs get merged (as to avoid time consumming conflicts handing)

**Comment by royclarkson** [comment]
> To apply smart nulls to all app broker tests requires converting tests using BDDMockito (in form of given(object.method()).willReturn(value) into doReturn(value).when(object.method())

Is this absolutely necessary? It was an effort to convert everything _to_ BDDMockito. 😅

**Comment by gberche-orange** [comment]
> Is this absolutely necessary? It was an effort to convert everything to BDDMockito. 

https://stackoverflow.com/a/15835255/1484823 details why BDDMockito can't be used with small nulls

> Note that you cannot use `when` with this functionality, since the method is called before `when` ([How does mockito when() invocation work?](https://stackoverflow.com/questions/14440270/how-does-mockito-when-invocation-work)) and it will throw a RuntimeException before the mock goes into stubbing mode.
>
> Therefore, you must use `doReturn` for this to work.

I'm sorry if this feels like going backwards. I hope that friendly exceptions will save plenty of time to app broker maintainers when tests need change, and will outweight the readability benefits of BDDMockito. Hopefully the "intellij structural search and replace" practice should make it easier to apply future similar syntax changes in used libraries.

**Comment by MRamonLeon** [comment]
``` @Mock(answer = Answers.RETURNS_SMART_NULLS)```
saved my day 🙇🏽‍♂️
