### ISSUE TITLE
ServiceInstanceRecentLogsTest > shouldFetchLogs() FAILED (1.1.x)

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#448]
Test failure on the 1.1.x branch

```
ServiceInstanceRecentLogsTest > shouldFetchLogs() FAILED
    java.lang.IllegalStateException: Timeout on blocking read for 5000 MILLISECONDS
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
        at reactor.core.publisher.Mono.block(Mono.java:1703)
        at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultRequestBodyUriSpec.exchange(DefaultWebTestClient.java:307)
        at org.springframework.cloud.appbroker.logging.recent.ServiceInstanceRecentLogsTest.shouldFetchLogs(ServiceInstanceRecentLogsTest.java:92)
```

**Comment by spikymonkey** [comment]
Fixed by #459
